# Generated by Django 3.2.8 on 2024-11-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20241119_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveField(
            model_name='task',
            name='order',
        ),
    ]
